services:
  postgres:
    image: postgres:14-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA='/var/lib/postgresql/data/pgdata'
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - app
    volumes:
      - redis-data:/bitnami/redis/data
    command: /bin/sh -c 'if [ -n "$REDIS_PASS" ]; then redis-server --requirepass "$REDIS_PASS"; else redis-server; fi'
  
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bot:latest
    container_name: tg_bot_template
    restart: always
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres
      - redis

networks:
  app:
    driver: bridge

volumes:
  postgres-data: {}
  redis-data: {}